In [1]:
%load_ext autoreload
%autoreload 2

In [8]:
import molsysmt as msm
import openinterface as oin
from matplotlib import pyplot as plt
import nglview as nv
import numpy as np
from simtk import unit

In [3]:
molecular_system=msm.convert("HIF1_HS_Mod.pdb")

In [4]:
msm.info(molecular_system)

## Buried factors

In [ ]:
buried_factors_receptor, buried_factors_ligand, labels_receptor, labels_ligand = \
oin.buried_factors(molecular_system, 'component_index==0', 'component_index==1')

In [ ]:
view = nv.show_molsysmt(molecular_system)
view.clear()
buried_factors_all = np.hstack([buried_factors_receptor, buried_factors_ligand])
msm.nglview.show_colored_surface_by_scalar_residue_values(view, buried_factors_all[0,:])
view

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==0")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, buried_factors_receptor[0,:])
view

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==1")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, buried_factors_ligand[0,:])
view

## Contact map and connectivity

### Contact map

In [ ]:
contact_map, labels_receptor, labels_ligand = \
oin.contact_map(molecular_system,'component_index==0', 'component_index==1')

In [ ]:
plt.imshow(contact_map[0], cmap='Greys', origin='lower')
plt.show()

### Connectivity

In [ ]:
connectivity_receptor, connectivity_ligand, labels_receptor, labels_ligand = \
oin.connectivity(molecular_system, 'component_index==0', 'component_index==1')

In [ ]:
plt.scatter(connectivity_ligand[0], buried_factors_ligand[0])
plt.show()

In [ ]:
plt.scatter(connectivity_receptor[0], buried_factors_receptor[0])
plt.show()

In [ ]:
view = nv.show_molsysmt(molecular_system)
view.clear()
connectivity_all = np.hstack([connectivity_receptor, connectivity_ligand])
msm.nglview.show_colored_surface_by_scalar_residue_values(view, connectivity_all[0,:])
view

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==0")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, connectivity_receptor[0,:])
view

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==1")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, connectivity_ligand[0,:])
view

### Nearby Connectivity

In [ ]:
nearby_connectivity_receptor, nearby_connectivity_ligand, labels_receptor, labels_ligand = \
oin.connectivity(molecular_system, 'component_index==0', 'component_index==1')

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==0")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, nearby_connectivity_receptor[0,:])
view

In [ ]:
view = nv.show_molsysmt(molecular_system, selection="component_index==1")
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, nearby_connectivity_ligand[0,:])
view

## Contacting residues

In [59]:
residues_rec, residues_lig = oin.contacting_residues(molecular_system, 'component_index==0', 'component_index==1')

In [60]:
residues_rec

array([339, 340, 360, 361, 362, 363, 364, 365, 366])

In [61]:
residues_lig

array([367, 368, 369, 370, 371, 372, 373, 374, 391, 392])

In [55]:
n_residues_rec = msm.get(molecular_system, selection='component_index==0', n_groups=True)
n_residues_lig = msm.get(molecular_system, selection='component_index==1', n_groups=True)

In [63]:
pinto_contactos = np.zeros(n_residues_rec)
pinto_contactos[residues_rec]=1.0

In [64]:
view = nv.show_molsysmt(molecular_system, selection='component_index==0')
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, pinto_contactos)
view

NGLWidget()

In [65]:
pinto_contactos = np.zeros(n_residues_lig)
pinto_contactos[residues_lig-367]=1.0

In [67]:
residues_lig-367

array([ 0,  1,  2,  3,  4,  5,  6,  7, 24, 25])

In [66]:
view = nv.show_molsysmt(molecular_system, selection='component_index==1')
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, pinto_contactos)
view

NGLWidget()

## SASA buried

In [ ]:
oin.sasa_buried(molecular_system, 'component_index==0', 'component_index==1')

## Surface polarity

In [ ]:
polarity = msm.physchem.get_polarity(molecular_system, selection='component_index==0', target='group', polarity_type='grantham')

In [ ]:
view = nv.show_molsysmt(molecular_system, selection='component_index==0')
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, np.array(polarity))
view

In [ ]:
polarity = msm.physchem.get_polarity(molecular_system, selection='component_index==1', target='group', polarity_type='grantham')

In [ ]:
view = nv.show_molsysmt(molecular_system, selection='component_index==1')
view.clear()
msm.nglview.show_colored_surface_by_scalar_residue_values(view, np.array(polarity))
view

In [35]:
msm.physchem.get_radii(molecular_system, selection=[0,0,0,0,1,2,3], target='atom', radius_type='vdw')

[Quantity(value=155.0, unit=picometer),
 Quantity(value=155.0, unit=picometer),
 Quantity(value=155.0, unit=picometer),
 Quantity(value=155.0, unit=picometer),
 Quantity(value=170.0, unit=picometer),
 Quantity(value=170.0, unit=picometer),
 Quantity(value=152.0, unit=picometer)]